#define S_NEED_INST "NECESITAS INSTRUCCIONES (S/N)"
#define S_PRESS_KEY "PULSA UNA TECLA"

#define S_I_001 "Este programa simula el viaje"
#define S_I_002 "por la Ruta de Oregon, desde"
#define S_I_003 "Indepencende, Missouri hasta"
#define S_I_004 "la Ciudad de Oregon, Oregon, en"
#define S_I_005 "1847."
#define S_I_006 "Los cinco que formais la familiadebeis cubrir las 2040 millas"
#define S_I_007 "que forman la ruta de Oregon"
#define S_I_008 "En 5-6 Meses --- Si llegais con"
#define S_I_009 "vida..."
#define S_I_010 "Has Ahorrado $900 para gastar enel viaje, y acabas de pagar $200";
#define S_I_011 "por una carreta."
#define S_I_012 "Necesitas gastar el resto de"
#define S_I_013 "tu dinero en alguno de los"
#define S_I_014 "siguientes elementos:"
#define S_I_015 "BUEYES - Debes gastar entre"
#define S_I_016 "     $200-300 en el equipo,"
#define S_I_017 "     a mas gastes, mas rapido"
#define S_I_018 "     iras ya que tendras mejores";
#define S_I_019 "     animales"
#define S_I_020 "COMIDA - Cuanta mas tengas, "
#define S_I_021 "     menores posibilidades de"
#define S_I_022 "     caer enfermo"
#define S_I_023 "MUNICION - $1 compra un cinturon";
#define S_I_024 "     con 50 balas, las necesitas";
#define S_I_025 "     contra los ataques de los"
#define S_I_026 "     animales y bandidos y para"
#define S_I_027 "     cazar comida"
#define S_I_028 "ROPA - Es especialmente impor-"
#define S_I_029 "     tante para combatir el frio";
#define S_I_030 "     que te encontraras al"
#define S_I_031 "     cruzar las montanas"
#define S_I_032 ""

#define S_I_033 "SUMINISTROS VARIOS - Estos"
#define S_I_034 "     incluyen medicinas y otras"
#define S_I_035 "     cosas que necesitaras por"
#define S_I_036 "     las enfermedades y para"
#define S_I_037 "     reparaciones de emergencia"
#define S_I_038 "Puedes gastar todo tu dinero"
#define S_I_039 "antes de iniciar el viaje --"
#define S_I_040 "O puedes guardar algo de dinero"
#define S_I_041 "para gastar en los fuertes que"
#define S_I_042 "encontraras en el camino. "
#define S_I_043 "No obstante, las cosas son mas"
#define S_I_044 "caras en los fuertes. Tambien"
#define S_I_045 "puedes cazar por el camino para"
#define S_I_046 "consegir mas comida."

#define S_I_047 "Siempre que debas usar tu fiel"
#define S_I_048 "rifle a lo largo del camino,"
#define S_I_049 "se te pedira que teclees una"
#define S_I_050 "palabra (Una parecida al sonido"
#define S_I_051 "de un disparo). A mas rapido"
#define S_I_052 "la teclees y pulses ""ENTER"""
#define S_I_053 "mayores seran tus posibilidades"
#define S_I_054 "de acertar con el arma."

#define S_I_055 "En cada turno, tu inventario "
#define S_I_056 "se mostrara por el precio en $"
#define S_I_057 "excepto las balas."
#define S_I_058 "Cuando te pregunte por una"
#define S_I_059 "Cantidad de dinero no uses el   simbolo ""$"""
#define S_I_060 "BUENA SUERTE!!!"

#define S_ACE_01 "COMO DE BUENO ERES DISPARANDO"
#define S_ACE_02 "CON UN  RIFLE?"
#define S_ACE_03 "  (1) AS DE LA DIANA"
#define S_ACE_04 "  (2) BUEN TIRADOR"
#define S_ACE_05 "  (3) POR ENCIMA DE LA MEDIA"
#define S_ACE_06 "  (4) NECESITO PRACTICAR"
#define S_ACE_07 "  (5) ME TIEMBLAN LAS RODILLAS"
#define S_ACE_08 "ELIJE ENTRE UNO DE ESTOS --"
#define S_ACE_09 "CUANTO MEJOR DIGAS QUE ERES"
#define S_ACE_10 "MAS RAPIDO TENDRAS QUE SER CON"
#define S_ACE_11 "TU ARMA PARA SALIR ADELANTE"

#define S_HOW_MUCH_OX "Cuanto vas a gastar en el grupo de bueyes:"
#define S_HOW_MUCH_FOOD "Cuanto vas a gastar en comida:"
#define S_HOW_MUCH_BULLET "Cuanto vas a gastar en municion:";
#define S_HOW_MUCH_CLOTHES "Cuanto vas a gastar en ropa:"
#define S_HOW_MUCH_OTHERS "Cuanto vas a gastar en el resto de cosas:"
#define S_NOT_ENOUGHT "No es suficiente"
#define S_TOO_MUCH "Es demasiado"
#define S_SPEND_MUCH_1 "TE HAS PASADO GASTANTO"
#define S_SPEND_MUCH_2 "Solo tienes $700 para"
#define S_SPEND_MUCH_3 "gastar, prueba otra vez."
#define S_AFTER_BUY_1 "Despues de las compras"
#define S_AFTER_BUY_2 "te quedan $"
#define S_AFTER_BUY_3 ""

#define S_IMPOSSIBLE "IMPOSIBLE"
#define S_FOOD "COMIDA: "
#define S_BULLETS "BALAS: "
#define S_AMMUNITION "MUNICION: "
#define S_CLOTHING "ROPA: "
#define S_MISC_SUPPLIES "EQUIPOS VARIOS: "
#define S_CASH "DINERO: $"
#define S_TOTAL_MILEAGE "DISTANCIA RECORRIDA: "
#define S_FOOD_LOW "DEBERIAS CAZAR O COMPRAR COMIDA PRONTO!!!!"
#define S_BILL_DOCTOR "La factura del Doctor son $20"

#define S_EAT1 "***COMIENDO***"
#define S_EAT2 "Como quieres comer:" 
#define S_EAT3 "(1) Pobremente"
#define S_EAT4 "(2) Moderadamente"
#define S_EAT5 "(3) Copiosamente"
#define S_EAT_MUCH "NO PUEDES COMER TANTO"
#define S_CHOOSE_23 "Quieres: (1) Cazar, o (2) Seguir"
#define S_CHOOSE_12 "Quieres:  (1) Parar en el siguiente fuerte,"
#define S_CHOOSE_3 "(2) Cazar, o (3) Seguir"
#define S_TYPE "TECLEA: "
#define S_EJEM_BULLETS "EJEM -- Necesitas balas para ir de caza"
#define S_AT_FORT "*** PARANDO EN EL FUERTE ***"
#define S_ENTER_HOW_MUCH "INTRODUCE CUANTO QUIRERES GASTAR EN LO SIGUIENTE:"
#define S_DONT_HAVE_SUCH "NO TIENES TANTO -- Manten tus compras por debajo"

#define S_HUNTING "*** DE CAZA ***"
#define S_HUNT_1 "BUEN DISPARO - JUSTO EN EL BLANCO -- Esta noche habra buena cena!"
#define S_HUNT_2 "JUSTO ENTRE LOS OJOS - HAS      PILLADO UNO GRANDE!!"
#define S_HUNT_3 "Esta noche las barrigas estaran a rebentar"
#define S_HUNT_4 "HAS FALLADO -- Tu cena ha escapado..."

#define S_RIDERS_01 "APARECEN BANDIDOS. Ellos"
#define S_RIDERS_02 " no"
#define S_RIDERS_03 " parecen hostiles"
#define S_RIDERS_04 "TACTICAS"
#define S_RIDERS_05 "(1) Correr  (2) Atacar  (3) Continuar  (4) Circulo de Carretas"
#define S_RIDERS_11 "BUEN DISPARO -- Te defiendes"
#define S_RIDERS_12 "SONOROS DISPARO -- Te han dado"
#define S_RIDERS_13 "Deberias ir a ver al viejo doctor Blanchard"
#define S_RIDERS_14 "Demasiado lento con tu COLT .45"
#define S_RIDERS_21 "Ellos no atacan"
#define S_RIDERS_22 "Los bandidos parecen amables, pero comprueba tus cosas"
#define S_RIDERS_23 "Los bandidos fueron hostiles -- comprueba las perdidas" 
#define S_RIDERS_24 "Te quedaste sin balas y los bandidos te masacran"

#define S_DIE_NO_FOOD "TE HAS QUEDADO SIN COMIDA Y MUERES DE HAMBRE"
#define S_DIE_NO_DOCTOR "NO TE PUEDES PERMITIR UN DOCTOR"
#define S_DIE_NO_MEDICAL "TE HAS QUEDADO SIN SUMINISTROS MEDICOS"
#define S_DIE_YOU "Mueres de "
#define S_DIE_ILL1 "Disenteria"
#define S_DIE_ILL2 "Neumonia"
#define S_DIE_INJURIES "las heridas"
#define S_DIE_01 "Debido a esta desafortunada     situacion, hay una serie de"
#define S_DIE_02 "formalidades por las que debemos pasar:"
#define S_DIE_03 "Desea un sacerdote?"
#define S_DIE_04 "Desea un funeral pomposo?"
#define S_DIE_05 "Desaa que avisemos a su familiarmas cercano?"
#define S_DIE_06 "Pero su tia Sadie en St. Louis esta realmente preocupada por usted"
#define S_DIE_07 "El coste del telegrama son $4.50"
#define S_DIE_08 "Le agradecemos la informacion y le acompanamos en el sentimiento"
#define S_DIE_09 "No ha conseguido alcanzar el    gran territorio de Oregon"
#define S_DIE_10 "La proxima vez tendra mejor     suerte."
#define S_DIE_11 "Sinceramente:"
#define S_DIE_12 "La camara de comercio de Oregon"
 
#define S_FIRST_DATE "Lunes, 29 de Marzo de 1847"
#define S_MONDAY "Lunes, "
#define S_04_12 "12 de Abril de "
#define S_04_26 "26 de Abril de "
#define S_05_10 "10 de Mayo de "
#define S_05_24 "24 de Mayo de "
#define S_06_07 "7 de Junio de "
#define S_06_21 "21 de Junio de "
#define S_07_05 "5 de Julio de "
#define S_07_19 "19 de Julio de "
#define S_08_02 "2 de Agosto de "
#define S_08_16 "16 de Agosto de "
#define S_08_31 "31 de Agosto de "
#define S_09_13 "13 de Septiembre de "
#define S_09_27 "27 de Setiembre de "
#define S_10_11 "11 de Octubre de "
#define S_10_25 "25 de Octubre de "
#define S_11_08 "8 de Noviembre de "
#define S_11_22 "22 de Noviembre de "
#define S_12_06 "6 de Diciembre de "
#define S_12_20 "20 de Diciembre de "
#define S_YEAR "1847"
#define S_TRAIL_TOO_LONG "HAS ESTADO DEMASIADO TIEMPO EN EL CAMINO  ------"
#define S_FAMILY_DIES "TU FAMILIA MUERE EN LA PRIMER TORMENTA DE GRANIZO DEL INVIERNO"

#define S_END1 "HAS LLEGADO FINALMENTE A LA     CIUDAD DE OREGON"
#define S_END2 "TRAS 2040 MILLAS --- HURRA!!!!!"
#define S_END3 "UN VERDADERO PIONERO!"
#define S_CMONDAY "LUNES, "
#define S_CTUESDAY "MARTES, "
#define S_CWEDNESDAY "MIERCOLES, "
#define S_CTHRUSDAY "JUEVES, "
#define S_CFRIDAY "VIERNES "
#define S_CSATURDAY "SABADO "
#define S_CSUNDAY "DOMINGO "
#define S_CJULY " DE JULIO DE "
#define S_CAUGUST " DE AUGOSTO DE "
#define S_CSEPTEMBER " DE SEPTIEMBRE DE "
#define S_COCTOBER " DE OCTUBRR DE"
#define S_CNOVEMBER " DE NOVIEMBRE DE"
#define S_CDECEMBER " DE DICIEMBRE DE"

#define S_EVENT " *** EVENTOS POR EL CAMINO ***"
#define S_WAGON_BREAK "EL CARROMATO SE ROMPE -- Pierdes tiempo y suministros arreglandolo"
#define S_OX_INJURED "UN BUEY SE HIERE EN UNA PATA -- Esto te retrasara el resto del viaje"
#define S_BROKE_ARM "MALA SUERTE -- Tu hija se rompe un brazo"
#define S_MAKE_SLING "Tienes que parar y gastar suministros en hacerle un cabestrillo"
#define S_OX_WANDER "UN BUEY SE ESCAPA -- Pierdes    tiempo buscandolo"
#define S_SON_LOST "TU HIJO SE PIERDE -- Pierdes medio dia buscandolo"
#define S_UNSAFE_WATER "AGUA CONTAMINADA -- Pierdes tiempo buscando una fuente limpia" 
#define S_HEAVY_RAINS "FUERTES LLUVIAS -- Pierdes tiempo y suministros" 
#define S_BANDITS_ATTACK "ATAQUE DE BANDIDOS"
#define S_OUT_BULLETS "TE QUEDASS SIN BALAS -- Te roban un monton de dinero"
#define S_SHOT_LEG "Te pegan un tiro en la pierna y se llevan uno de tus bueyes"
#define S_BETTER_SEE_DOC "Seria conveniente que un doctor le echase un vistazo a esa herida"
#define S_QUICKY "EL MAS RAPIDO AL OESTE DE PECOS!";
#define S_GOT_EM "LES HAS DADO!"
#define S_WAGON_FIRE "FUEGO EN EL CARROMATO -- Se dañan comida y suministros!"
#define S_LOSE_FOG "TE PIERDES EN LA NIEBLA -- Pier-des tiempo"
#define S_KILL_SNAKE "Matas una serpiente venenosa despues de que te mordiera"
#define S_SNAKE_KILL "Mueres por el mordisco, no tenias medicinas"
#define S_WAGON_SWAMPED "CARROMATO ATASCADO AL FONDEAR UNRIO -- Pierdes comida y sumi-   nistros"
#define S_WILD_ANIMALS "ATAQUE DE ANIMALES SALVAJES!"
#define S_LOW_BULLETS "NO TIENES BALAS SUFICIENTES --"
#define S_WOLVE_OVER "Los Lobos te superan"
#define S_NICE_SHOT "BUEN DISPARO COMPANERO -- No han conseguido mucho"
#define S_SLOW_DRAW "MUY LENTO -- Se han llevado ropa y comida"
#define S_COLD_WEATHER "TIEMPO FRIO --- BRRRRRRR! --- Tu"
#define S_DONT "no "
#define S_NO_CLOTHS "tienes ropa suficiente para     calentarte"
#define S_HAIL_STORM "TORMENTA DE GRANIZO--Suministrosdanados"
#define S_HELPFUL_INDIANS "Unos Amables Indios te muestran donde encontrar mas comida"

#define S_RUGGED_M "MOUNTANAS ROCOSAS"
#define S_LOST_TRAIL "TE HAS PERDIDO -- Pierdes un tiempo precioso tratando de encontrar el canimo!"
#define S_WAGON_DAMAGED "CARROMATO DANADO! -- Pierdes tiempo y suministros"
#define S_GOING_SLOW "Estas yendo muy lento"
#define S_YOU_MADE "HAS CONSEGUIDO ATRAVESAR EL PASO DEL SUR -- No hay nieve"
#define S_BLIZZARD "TORMENTA DE NIEVE EN EL PASO DE LAS MONTANAS -- Tiempo y sumi-  nistros perdidos"

#define S_ILL_SERIOUS "ENFERMEDAD SERIA --"
#define S_ILL_MEDICAL "Debes parar por atencion medica"
#define S_ILL_WILD "ENFERMEDAD SALVAJE --- Usaste   Medicinas"
#define S_ILL_BAD "ENFERMEDAD CHUNGA --- Usaste    Medicinas"

#define S_END_01 "        EL PRESIDENTE"
#define S_END_02 "        James K. Polk" 
#define S_END_03 "       Le envia sus mas"
#define S_END_04 "  Fervientes Felicitaciones"
#define S_END_05 "       y le desea una" 
#define S_END_06 "  prospera vida en adelante"
#define S_END_07 "      EN SU NUEVO HOGAR"
#define S_OTHER_PLAY "QUIERES VOLVER A JUGAR(S/N)?"






